@startuml
skinparam classAttributeIconSize 0
class MagicCube{
    - int spellCompleteDegree;
    - int spellCompleteSide
}
abstract class Spell{
    + complete :void
    + spellAllAround : void
    + spellButtomCross : void
    + spellButtomSide : void
    + spellPartOfAround : void
    + spellTopSide : void
    + magicCube : void
}
class ConcreteSpell{
    + complete :void
    + spellAllAround : void
    + spellButtomCross : void
    + spellButtomSide : void
    + spellPartOfAround : void
    + spellTopSide : void
    + magicCube : void
}
class People {
    + spellMagicCube :MagicCube
    + spell : Spell
}
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml